const acounts = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-02-15",
    lastLogin: "2024-02-20",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    type: "seller",
    status: "active",
    joinDate: "2024-02-10",
    lastLogin: "2024-02-19",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael@example.com",
    type: "customer",
    status: "inactive",
    joinDate: "2024-01-05",
    lastLogin: "2024-01-25",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@example.com",
    type: "seller",
    status: "active",
    joinDate: "2024-03-01",
    lastLogin: "2024-03-05",
  },
  {
    id: 5,
    name: "Daniel Brown",
    email: "daniel@example.com",
    type: "admin",
    status: "active",
    joinDate: "2023-12-01",
    lastLogin: "2024-02-18",
  },
  {
    id: 6,
    name: "Sophia Wilson",
    email: "sophia@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-01-20",
    lastLogin: "2024-02-22",
  },
  {
    id: 7,
    name: "William Taylor",
    email: "william@example.com",
    type: "seller",
    status: "inactive",
    joinDate: "2023-11-15",
    lastLogin: "2024-01-10",
  },
  {
    id: 8,
    name: "Isabella Martinez",
    email: "isabella@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-02-05",
    lastLogin: "2024-02-21",
  },
  {
    id: 9,
    name: "James Lee",
    email: "james@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-01-10",
    lastLogin: "2024-02-16",
  },
  {
    id: 10,
    name: "Olivia Anderson",
    email: "olivia@example.com",
    type: "seller",
    status: "active",
    joinDate: "2024-02-12",
    lastLogin: "2024-02-18",
  },
  {
    id: 11,
    name: "Benjamin Clark",
    email: "benjamin@example.com",
    type: "admin",
    status: "active",
    joinDate: "2023-12-15",
    lastLogin: "2024-02-22",
  },
  {
    id: 12,
    name: "Mia Walker",
    email: "mia@example.com",
    type: "customer",
    status: "inactive",
    joinDate: "2024-01-25",
    lastLogin: "2024-02-10",
  },
  {
    id: 13,
    name: "Henry Allen",
    email: "henry@example.com",
    type: "seller",
    status: "active",
    joinDate: "2024-02-01",
    lastLogin: "2024-02-20",
  },
  {
    id: 14,
    name: "Ava Scott",
    email: "ava@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-02-15",
    lastLogin: "2024-02-23",
  },
  {
    id: 15,
    name: "Lucas Green",
    email: "lucas@example.com",
    type: "seller",
    status: "inactive",
    joinDate: "2023-10-05",
    lastLogin: "2024-01-01",
  },
  {
    id: 16,
    name: "Ella Adams",
    email: "ella@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-02-18",
    lastLogin: "2024-02-23",
  },
  {
    id: 17,
    name: "Ethan Baker",
    email: "ethan@example.com",
    type: "admin",
    status: "active",
    joinDate: "2023-11-01",
    lastLogin: "2024-02-20",
  },
  {
    id: 18,
    name: "Charlotte Perez",
    email: "charlotte@example.com",
    type: "customer",
    status: "active",
    joinDate: "2024-02-10",
    lastLogin: "2024-02-22",
  },
  {
    id: 19,
    name: "Jack White",
    email: "jack@example.com",
    type: "seller",
    status: "active",
    joinDate: "2024-02-08",
    lastLogin: "2024-02-19",
  },
  {
    id: 20,
    name: "Amelia King",
    email: "amelia@example.com",
    type: "customer",
    status: "inactive",
    joinDate: "2024-01-15",
    lastLogin: "2024-01-30",
  },
];

export default acounts;
