const brandsByCategory = {
    Phones: [
        "Apple",
        "Samsung",
        "Google",
        "OnePlus",
        "Xiaomi",
        "Oppo",
        "Realme",
        "Motorola",
        "Huawei",
        "Sony",
        "Asus",
        "Vivo",
    ],
    Headphones: [
        "Sony",
        "Bose",
        "Apple",
        "Sennheiser",
        "JBL",
        "Beats by Dre",
        "Bang & Olufsen",
        "Skullcandy",
        "Audio-Technica",
        "Razer",
        "Anker Soundcore",
        "Shure",
    ],
    "Smart Watches": [
        "Apple",
        "Samsung",
        "Garmin",
        "Fitbit",
        "Huawei",
        "Amazfit",
        "Fossil",
        "Suunto",
        "Withings",
        "Xiaomi",
        "TicWatch (Mobvoi)",
    ],
};
