const orders1 = [
  {
    id: "#965",
    type: "dine in",
    customer: "Youssef",
    date: "Wed July 12, 2023",
    time: "06:12 PM",
    items: [
      { name: "PC Portable", qty: 1, price: 16.66 },
      { name: "Phone", qty: 2, price: 16.66 },
      { name: "Headphone", qty: 3, price: 16.66 },
    ],
    total: 87.56,
  },
  {
    id: "#966",
    type: "delivery",
    customer: "Amine",
    date: "Thu July 13, 2023",
    time: "02:45 PM",
    items: [
      { name: "Laptop", qty: 1, price: 899.99 },
      { name: "Mouse", qty: 1, price: 19.99 },
    ],
    total: 919.98,
  },
  {
    id: "#967",
    type: "dine in",
    customer: "Fatima",
    date: "Fri July 14, 2023",
    time: "12:30 PM",
    items: [
      { name: "Pizza", qty: 1, price: 12.5 },
      { name: "Pasta", qty: 2, price: 10.0 },
      { name: "Soft Drink", qty: 2, price: 3.0 },
    ],
    total: 38.5,
  },
  {
    id: "#968",
    type: "take away",
    customer: "Amina",
    date: "Sat July 15, 2023",
    time: "08:15 PM",
    items: [
      { name: "Burger", qty: 2, price: 7.99 },
      { name: "Fries", qty: 1, price: 3.5 },
      { name: "Milkshake", qty: 1, price: 4.5 },
    ],
    total: 23.97,
  },
  {
    id: "#969",
    type: "delivery",
    customer: "Karim",
    date: "Mon July 17, 2023",
    time: "07:00 PM",
    items: [
      { name: "Chicken Sandwich", qty: 1, price: 6.99 },
      { name: "Lemonade", qty: 2, price: 2.5 },
    ],
    total: 11.99,
  },
  {
    id: "#970",
    type: "dine in",
    customer: "Sofia",
    date: "Tue July 18, 2023",
    time: "01:20 PM",
    items: [
      { name: "Salad", qty: 1, price: 5.99 },
      { name: "Soup", qty: 1, price: 4.5 },
      { name: "Coffee", qty: 1, price: 3.0 },
    ],
    total: 13.49,
  },
  {
    id: "#971",
    type: "take away",
    customer: "Mohamed",
    date: "Wed July 19, 2023",
    time: "09:40 AM",
    items: [
      { name: "Croissant", qty: 2, price: 2.5 },
      { name: "Juice", qty: 1, price: 3.0 },
    ],
    total: 8.0,
  },
  {
    id: "#972",
    type: "delivery",
    customer: "Yasmine",
    date: "Thu July 20, 2023",
    time: "06:00 PM",
    items: [
      { name: "Fish Platter", qty: 1, price: 18.99 },
      { name: "Salad", qty: 1, price: 5.99 },
      { name: "Dessert", qty: 1, price: 6.0 },
    ],
    total: 30.98,
  },
  {
    id: "#973",
    type: "dine in",
    customer: "Omar",
    date: "Fri July 21, 2023",
    time: "07:45 PM",
    items: [
      { name: "Steak", qty: 1, price: 25.0 },
      { name: "Wine", qty: 2, price: 8.0 },
    ],
    total: 41.0,
  },
  {
    id: "#974",
    type: "take away",
    customer: "Lina",
    date: "Sat July 22, 2023",
    time: "10:00 AM",
    items: [
      { name: "Bagel", qty: 1, price: 4.5 },
      { name: "Coffee", qty: 1, price: 3.0 },
    ],
    total: 7.5,
  },
  {
    id: "#975",
    type: "delivery",
    customer: "Ahmed",
    date: "Sun July 23, 2023",
    time: "03:30 PM",
    items: [
      { name: "Grilled Chicken", qty: 1, price: 14.99 },
      { name: "Rice", qty: 1, price: 3.5 },
    ],
    total: 18.49,
  },
  {
    id: "#976",
    type: "dine in",
    customer: "Salma",
    date: "Mon July 24, 2023",
    time: "02:00 PM",
    items: [
      { name: "Pasta", qty: 1, price: 10.0 },
      { name: "Soft Drink", qty: 1, price: 3.0 },
    ],
    total: 13.0,
  },
  {
    id: "#977",
    type: "take away",
    customer: "Hassan",
    date: "Tue July 25, 2023",
    time: "11:15 AM",
    items: [
      { name: "Sandwich", qty: 1, price: 5.99 },
      { name: "Smoothie", qty: 1, price: 4.0 },
    ],
    total: 9.99,
  },
  {
    id: "#978",
    type: "delivery",
    customer: "Rania",
    date: "Wed July 26, 2023",
    time: "08:30 PM",
    items: [
      { name: "Seafood Platter", qty: 1, price: 22.5 },
      { name: "Dessert", qty: 1, price: 6.0 },
    ],
    total: 28.5,
  },
  {
    id: "#979",
    type: "dine in",
    customer: "Hana",
    date: "Thu July 27, 2023",
    time: "07:00 PM",
    items: [
      { name: "Pizza", qty: 2, price: 12.5 },
      { name: "Beer", qty: 1, price: 5.0 },
    ],
    total: 30.0,
  },
  {
    id: "#980",
    type: "take away",
    customer: "Younes",
    date: "Fri July 28, 2023",
    time: "01:30 PM",
    items: [
      { name: "Hot Dog", qty: 1, price: 3.5 },
      { name: "Fries", qty: 1, price: 3.0 },
    ],
    total: 6.5,
  },
  {
    id: "#981",
    type: "delivery",
    customer: "Khadija",
    date: "Sat July 29, 2023",
    time: "06:45 PM",
    items: [
      { name: "Salmon", qty: 1, price: 15.99 },
      { name: "Wine", qty: 1, price: 8.0 },
    ],
    total: 23.99,
  },
  {
    id: "#982",
    type: "dine in",
    customer: "Samir",
    date: "Sun July 30, 2023",
    time: "08:00 PM",
    items: [
      { name: "Steak", qty: 1, price: 25.0 },
      { name: "Mashed Potatoes", qty: 1, price: 6.0 },
    ],
    total: 31.0,
  },
  {
    id: "#983",
    type: "take away",
    customer: "Zahra",
    date: "Mon July 31, 2023",
    time: "12:00 PM",
    items: [
      { name: "Wrap", qty: 1, price: 5.5 },
      { name: "Soda", qty: 1, price: 2.0 },
    ],
    total: 7.5,
  },
  {
    id: "#984",
    type: "delivery",
    customer: "Nour",
    date: "Tue August 1, 2023",
    time: "02:30 PM",
    items: [
      { name: "Biryani", qty: 1, price: 12.0 },
      { name: "Dessert", qty: 1, price: 6.0 },
    ],
    total: 18.0,
  },
];

export default orders1;
