const saller = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    business: "Tech Store",
    status: "pending",
    date: "2024-02-20",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    business: "Fashion Boutique",
    status: "approved",
    date: "2024-02-19",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael@example.com",
    business: "Gadget World",
    status: "rejected",
    date: "2024-02-18",
  },
  {
    id: 4,
    name: "Emily Johnson",
    email: "emily@example.com",
    business: "Home Decor Shop",
    status: "approved",
    date: "2024-02-17",
  },
  {
    id: 5,
    name: "Daniel Taylor",
    email: "daniel@example.com",
    business: "Fitness Gear",
    status: "pending",
    date: "2024-02-16",
  },
  {
    id: 6,
    name: "Sophia Wilson",
    email: "sophia@example.com",
    business: "Beauty & Skincare",
    status: "approved",
    date: "2024-02-15",
  },
  {
    id: 7,
    name: "William Martinez",
    email: "william@example.com",
    business: "Sports Supplies",
    status: "rejected",
    date: "2024-02-14",
  },
  {
    id: 8,
    name: "Olivia Clark",
    email: "olivia@example.com",
    business: "Organic Market",
    status: "approved",
    date: "2024-02-13",
  },
  {
    id: 9,
    name: "James Anderson",
    email: "james@example.com",
    business: "Book Haven",
    status: "approved",
    date: "2024-02-12",
  },
  {
    id: 10,
    name: "Mia Robinson",
    email: "mia@example.com",
    business: "Toy Paradise",
    status: "pending",
    date: "2024-02-11",
  },
  {
    id: 11,
    name: "Lucas Perez",
    email: "lucas@example.com",
    business: "Pet Supplies",
    status: "approved",
    date: "2024-02-10",
  },
  {
    id: 12,
    name: "Charlotte Hill",
    email: "charlotte@example.com",
    business: "Jewelry Shop",
    status: "rejected",
    date: "2024-02-09",
  },
  {
    id: 13,
    name: "Benjamin Adams",
    email: "benjamin@example.com",
    business: "Digital Solutions",
    status: "pending",
    date: "2024-02-08",
  },
  {
    id: 14,
    name: "Amelia Lewis",
    email: "amelia@example.com",
    business: "Art Supplies Store",
    status: "approved",
    date: "2024-02-07",
  },
  {
    id: 15,
    name: "Henry Scott",
    email: "henry@example.com",
    business: "Gourmet Food Shop",
    status: "rejected",
    date: "2024-02-06",
  },
  {
    id: 16,
    name: "Ella Garcia",
    email: "ella@example.com",
    business: "Clothing Outlet",
    status: "approved",
    date: "2024-02-05",
  },
  {
    id: 17,
    name: "Ethan King",
    email: "ethan@example.com",
    business: "Automotive Parts",
    status: "pending",
    date: "2024-02-04",
  },
  {
    id: 18,
    name: "Isabella Turner",
    email: "isabella@example.com",
    business: "Stationery World",
    status: "approved",
    date: "2024-02-03",
  },
  {
    id: 19,
    name: "Jack Harris",
    email: "jack@example.com",
    business: "Electronics Hub",
    status: "approved",
    date: "2024-02-02",
  },
  {
    id: 20,
    name: "Zoe Walker",
    email: "zoe@example.com",
    business: "Travel Accessories",
    status: "pending",
    date: "2024-02-01",
  },
];

export default saller;
